mlcommons/tiny

- .gitmodules
The model generation code for audio based anomaly detection is derived from the DCASE 2020 competition's MIT licensed baseline model code.
> Linking anomaly detection model generation code as sub-module

- v0.1/reference_submissions/person_detection/README.md
Added **mbed config root .** which I had to call before **mbed deploy**
> readme update , vww moved to trained models

- v0.1/training/anomaly_detection/01_test.py
- v0.1/training/anomaly_detection/02_convert.py
- v0.1/training/anomaly_detection/common.py
Adding improvements to training scripts:
- generation of int8->int8 TFlite model version
- support saving histograms in various formats
> Anomaly detection input rebase

- v0.1/reference_submissions/anomaly_detection/setup_example.sh
- v0.1/training/anomaly_detection/convert_dataset.py
Enable faster inference using CMSIS-NN
> Use CMSIS-NN on the ARM platform

- v0.1/training/anomaly_detection/01_test.py
- v0.1/training/anomaly_detection/convert_dataset.py
- v0.1/training/anomaly_detection/eval_functions_eembc.py
Add calculation of metric as in shared code with EEMBC.
> EEMBC accuracy

- v0.1/reference_submissions/anomaly_detection/mbed-os.lib
- v0.1/reference_submissions/anomaly_detection/setup_example.sh
Fix some build errors and make sure the right Mbed version is used
> Anomaly Detection mbed version fixes

- v0.1/reference_submissions/anomaly_detection/mbed-os.lib
- v0.1/reference_submissions/anomaly_detection/setup_example.sh
- v0.1/reference_submissions/anomaly_detection/submitter_implemented.cpp
> Ad mbed version fixes

- v0.1/reference_submissions/person_detection/api/submitter_implemented.h
- v0.1/reference_submissions/person_detection/mbed-os.lib
- v0.1/reference_submissions/person_detection/mbed_app.json
- v0.1/reference_submissions/person_detection/setup_example_linux.sh
Runime down from ~8s to much less than 1s per inference
> Support CMSIS-NN and float formatting in printf

- v0.1/reference_submissions/anomaly_detection/submitter_implemented.cpp
annoying typo slipped through the checks
> fixup eembc patch

- v0.1/reference_submissions/anomaly_detection/submitter_implemented.cpp
move some init and post-processing code outside of the measured function
> AD: move data copy and post-processing outside of the measured function

- v0.1/reference_submissions/image_classification/submitter_implemented.cpp
> disable printing of integer result

- v0.1/training/anomaly_detection/trained_models/ToyCar/baseline_tf23/model/model_ToyCar.md5
- v0.1/training/anomaly_detection/trained_models/ToyCar/baseline_tf23/model/model_ToyCar_quant_fullint_micro_intio.md5
- v0.1/training/image_classification/trained_models/pretrainedResnet.md5
- v0.1/training/image_classification/trained_models/pretrainedResnet_quant.md5
- v0.1/training/keyword_spotting/trained_models/kws_ref_model.md5
- v0.1/training/visual_wake_words/trained_models/vww_96_float.md5
- v0.1/training/visual_wake_words/trained_models/vww_96_int8.md5
This PR adds an md5 hash to all of the official models. This hash will be used to check consistency between github repos, as these models will end up in multiple places.
> Added MD5 sums for all int8 official models.

- LICENSE.md
> Copying license from inference repo

- v0.5/README.md
Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>
> add references also at top level

- v0.5/training/visual_wake_words/generate_y_labels.py
Generates y_labels. This script must be run AFTER the raw images have been processed and saved as .bin
To save as .bin, use a script like https://github.com/SiliconLabs/platform_ml_models/blob/master/eembc/Person_detection/buildPersonDetectionDatabase.py but save as .bin instead of .jpg
> Add generate_y_lables script

- benchmark/README.md
Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>
> fixing links in README to point to benchmark folder

- README.md
- benchmark/MLPerfTiny_Rules.adoc
- benchmark/README.md
updated links, names, and some of the text to v0.7
> updates to READMEs for v0.7

- README.md
Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>
> add v0.7 release links

- README.md
Upldate README with links and dates
> add v1.0 release links

- .gitignore
- benchmark/training_torch/image_classification/README.md
- benchmark/training_torch/image_classification/download_cifar10_train_resnet.sh
- benchmark/training_torch/image_classification/prepare_training_env.sh
- benchmark/training_torch/image_classification/requirements.txt
- benchmark/training_torch/image_classification/test.py
- benchmark/training_torch/image_classification/train.py
- benchmark/training_torch/image_classification/utils/data.py
- benchmark/training_torch/image_classification/utils/model.py
- benchmark/training_torch/image_classification/utils/training.py
Hello and thank you for this useful benchmark! 
We (ENOT team) have submitted a pull request to the tiny repository that contains an image classification pipeline on PyTorch. We believe it can be beneficial for open submissions since PyTorch offers various specific techniques for model optimization compared to TensorFlow.
> Add training on PyTorch

- benchmark/MLPerfTiny_Rules.adoc
update rules to include more Tiny specific text and clarify submission of binaries
> Proposed rules update for v1.2, clarifying submission of binaries

- benchmark/training/streaming_wakeword/README.md
- benchmark/training/streaming_wakeword/requirements.txt
I've created a set of instructions for setting up the environment to get it working for myself, and thought it might be useful for others. This uses the environment shared by @jeremy-syn (https://github.com/mlcommons/tiny/issues/148).
> README setup and requirements.txt for Streaming Wake word

- tools/submission/generate_final_report.py
- tools/submission/requirements.txt
- tools/submission/submission_checker.py
- Add submission checker to the public repository.
- Add generate final report to the public repository.
- Configuration for v1.2 submission copied from v1.1 configuration.
> Add submission checker

- benchmark/runner/main.py
- benchmark/runner/power_manager.py
- benchmark/runner/script.py
- benchmark/runner/serial_device.py
Finally got everything figured out
Powerboard Implementation and code cleanup.
When running there is a new thing called mode
Performance
python main.py --dataset_path=C:\Users\robet\GitHubRepos\energyrunner\datasets --mode=p
Energy
python main.py --dataset_path=C:\Users\robet\GitHubRepos\energyrunner\datasets --mode=e
> PowerBoard LPM
